name: hello world
description: hello world
on: 
  push:
    branches:
      - master
jobs:
  Hello:
    runs-on: ubuntu-18.04
    steps:
      - run: go run main.go  # Run the go program
      - shell: bash           # Use bash shell
      - uses: actions/checkout@v3  # Checkout code from the repository
      - name: Hello World!
        run: echo "Hello World!"  # Print "Hello World!"